name: 🤖 Auto move new issues into Triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/project@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
