name: 🤖 Auto move new issues into Triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/project@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
