name: 🤖 Auto cleanup caches
on:
  push:
    branches: [main, 'v[0-9]+.x']
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiga-family/ci/actions/auto/cleanup-cache@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
        if: github.event_name == 'push'
        with:
          branch-name: ${{ github.head_ref || github.ref_name }}
      - uses: taiga-family/ci/actions/auto/cleanup-cache@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
        if: github.event_name == 'pull_request'
        with:
          branch-name: refs/pull/${{ github.event.pull_request.number }}/merge
