name: 🤖 Auto label
on: pull_request_review

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.87.8
      - uses: taiga-family/ci/actions/auto/label-when-approved@v1.87.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
