name: 🤖 Auto move new issues into Triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/project@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
