name: 🤖 Auto cleanup caches
on:
  push:
    branches: [main, 'v[0-9]+.x']
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: taiga-family/ci/actions/auto/cleanup-cache@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        if: github.event_name == 'push'
        with:
          branch-name: ${{ github.head_ref || github.ref_name }}
      - uses: taiga-family/ci/actions/auto/cleanup-cache@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        if: github.event_name == 'pull_request'
        with:
          branch-name: refs/pull/${{ github.event.pull_request.number }}/merge
