name: ⚙️ Bundle size
on:
  push:
    branches: [main]
  pull_request:

jobs:
  tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@3e1b1fc507d59ea30da7e951ae5d47e42f529586 # v1.194.0
      - uses: taiga-family/ci/actions/setup/node@3e1b1fc507d59ea30da7e951ae5d47e42f529586 # v1.194.0
      - run: npx nx build demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
