name: ⚙️ Bundle size
on:
  push:
    branches: [main]
  pull_request:

jobs:
  tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: taiga-family/ci/actions/setup/variables@v1.145.0
      - uses: taiga-family/ci/actions/setup/node@v1.145.0
      - run: npx nx build demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
        continue-on-error: true
        env:
          CI_COMMIT_SHA: ${{ env.CI_COMMIT_SHA }}
