name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.36.2
      - uses: taiga-family/ci/actions/setup/variables@v1.36.2
      - uses: taiga-family/ci/actions/setup/node@v1.36.2
      - run: npm run lint
      - run: npm run prettier -- --check
      - run: |
          rm -rf dist/demo
          npx nx prerender demo
          cp dist/demo/index.html dist/demo/404.html
          rm -rf dist/demo/server dist/demo/index.original.html

      - uses: taiga-family/ci/actions/deploy/github-pages@v1.36.2
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
