name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/ci/actions/setup/variables@c3c5b1dafd967e96aadf1cd4d589bd57fab81d43 # v2.18.0
      - uses: taiga-family/ci/actions/setup/node@c3c5b1dafd967e96aadf1cd4d589bd57fab81d43 # v2.18.0
      - run: npx nx build demo --base-href /preview-landing-components/
      - uses: taiga-family/ci/actions/deploy/github-pages@c3c5b1dafd967e96aadf1cd4d589bd57fab81d43 # v2.18.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
