name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.39.1
      - uses: taiga-family/ci/actions/setup/variables@v1.39.1
      - uses: taiga-family/ci/actions/setup/node@v1.39.1
      - run: npx nx build-gh-pages demo
      - uses: taiga-family/ci/actions/deploy/github-pages@v1.39.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
