name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.42.0
      - uses: taiga-family/ci/actions/setup/variables@v1.42.0
      - uses: taiga-family/ci/actions/setup/node@v1.42.0
      - run: npx nx build demo
      - uses: taiga-family/ci/actions/deploy/github-pages@v1.42.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
