name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/ci/actions/setup/variables@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - uses: taiga-family/ci/actions/setup/node@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - run: npx nx build demo
      - name: Debug output
        run: tree dist/demo/browser -P '*.html'
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAIGA_UI_PREVIEW_LANDING }}
          projectId: taiga-ui-preview-landing
          expires: 1d

concurrency:
  group: firebase-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
