name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/setup/node@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - run: npx nx build demo --base-href /preview-landing-components/
      - uses: taiga-family/ci/actions/deploy/github-pages@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
