name: ⚙️ E2E tests
on:
  pull_request:

env:
  RETRY_COUNT: 2
  PW_RESULT: ./apps/demo/e2e/tests-results
  FAILED_SCREENSHOTS_PATH: apps/demo/e2e/tests-results

jobs:
  e2e:
    name: E2E result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: taiga-family/ci/actions/setup/variables@v1.139.0
      - uses: taiga-family/ci/actions/setup/node@v1.139.0
      - uses: taiga-family/ci/actions/setup/playwright@v1.134.0
      - run: npx nx e2e demo -- --update-snapshots
      - run: BASE_URL=https://taiga-family.github.io/preview-landing-components/ npx nx e2e demo
        continue-on-error: true

      - name: Combine images to get diff reports
        run: |
          npm install canvas --no-save --silent --force
          npx ts-node -e "import { tuiCombinePlaywrightFailedScreenshots as run } from '@taiga-ui/testing/visual-testing'; run();";
      - name: Upload artifacts / ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ${{ env.PW_RESULT }}/**/*-retry${{ env.RETRY_COUNT }}/**/*.diff.png
          name: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
          if-no-files-found: ignore
          compression-level: 0
          retention-days: 1

      - name: Check if diff-output exists
        id: diff_checker
        run: |
          echo "diff_exist=$(find ${{ env.PW_RESULT }} -iname '*.diff.png' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff_checker.outputs.diff_exist != '0' }}
        run: |
          find ${{ env.PW_RESULT }} -iname '*.diff.png' -exec echo "{}" \;
          exit 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
