name: ⚙️ E2E tests
on:
  pull_request:

jobs:
  e2e:
    name: E2E result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: taiga-family/ci/actions/setup/variables@v1.148.0
      - uses: taiga-family/ci/actions/setup/node@v1.148.0
      - uses: taiga-family/ci/actions/setup/playwright@v1.148.0
      - run: npx nx e2e demo -- --update-snapshots
      - run: npx nx e2e demo
        continue-on-error: true
        env:
          BASE_URL: https://taiga-family.github.io/preview-landing-components/

      - uses: taiga-family/ci/actions/setup/playwright-combine-failed-screenshot@v1.148.0
        env:
          FAILED_SCREENSHOTS_PATH: apps/demo/e2e/tests-results

      - uses: taiga-family/ci/actions/setup/playwright-diff-check@v1.148.0
        with:
          pw-result: apps/demo/e2e/tests-results

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
