name: 🤖 Screenshot Report
on:
  workflow_run:
    workflows: [⚙️ E2E tests]
    types: [requested, completed]
  pull_request:
    types: [closed]

jobs:
  awake-screenshot-bot:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    steps:
      - uses: taiga-family/argus@c0ef50d202852eb1de55cc0ab436149ebb7a02b8 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
